# Generated by Django 5.0.6 on 2024-06-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cutoff_day", models.IntegerField()),
                ("pay_day", models.IntegerField()),
                ("limit", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "account_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.accountholder",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.bankname",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kredi Kartı",
                "verbose_name_plural": "Kredi Kartları",
            },
        ),
    ]
