# Generated by Django 5.0.6 on 2024-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankname",
            name="color",
            field=models.CharField(default="#efefef", max_length=7),
        ),
    ]
