# Generated by Django 5.0.6 on 2024-06-24 17:39

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0004_transaction_delete_banktransaction"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[(1, "Gelen"), (0, "Giden"), (2, "Transfer")]
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("date", models.DateField(default=datetime.date.today)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_after_transaction",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_transactions",
                        to="bank_accounts.bankaccount",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_transactions",
                        to="bank_accounts.bankaccount",
                    ),
                ),
                (
                    "transaction_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.otherholder",
                    ),
                ),
            ],
        ),
    ]
