# Generated by Django 5.0.6 on 2024-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0006_alter_transaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
