# Generated by Django 5.0.6 on 2024-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0007_alter_bankaccount_current_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
