# Generated by Django 5.0.6 on 2025-03-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0010_transaction_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
    ]
